// Shared styles and utility classes
export const styles = {
  container: "container mx-auto px-4 md:px-6 lg:px-8",
  section: "py-16 md:py-24",
  heading: "text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight",
  subheading: "text-2xl md:text-3xl lg:text-4xl font-bold",
  button: {
    primary: "px-6 py-3 bg-primary text-primary-foreground hover:bg-primary/90 transition-colors font-medium",
    outline:
      "px-6 py-3 border-2 border-primary text-primary hover:bg-primary hover:text-primary-foreground transition-colors font-medium",
  },
  overlay: "absolute inset-0 bg-black/40",
  fadeIn: "animate-fade-in",
} 

export const translations = {
  en: {
    about: "ABOUT",
    communities: "COMMUNITIES",
    projects: "PROJECTS",
    retail: "RETAIL",
    media: "MEDIA",
    events: "EVENTS",
    bookNow: "BOOK NOW",
    discover: "DISCOVER",
    visionaryCity: "A VISIONARY CITY",
    callsFor: "CALLS FOR",
    innovativeLiving: "INNOVATIVE LIVING",
    language: "العربية",
    luxuryLiving: "Luxury Living Redefined",
    exploreCommunities: "Explore Our Communities",
    worldClass: "World-Class Amenities",
    sustainableFuture: "Building a Sustainable Future",
    contactUs: "Contact Us",
    phone: "Phone",
    aboutUs: "About Us",
    ourStory: "Our Story",
    ourStoryDesc:
      "Since our inception, we have been at the forefront of luxury real estate development, creating iconic communities that redefine modern living. Our commitment to excellence and innovation has established us as a trusted name in the industry.",
    ourVision: "Our Vision",
    ourVisionDesc:
      "To create vibrant, sustainable communities that enhance the quality of life for residents while contributing to the urban landscape. We envision a future where luxury meets functionality, and innovation drives every aspect of development.",
    ourMission: "Our Mission",
    ourMissionDesc:
      "To deliver exceptional real estate developments that exceed expectations through innovative design, quality craftsmanship, and customer-centric approach. We are committed to building communities that stand the test of time.",
    coreValues: "Core Values",
    excellence: "Excellence",
    excellenceDesc: "We pursue the highest standards in every project we undertake.",
    innovation: "Innovation",
    innovationDesc: "We embrace cutting-edge technology and creative solutions.",
    integrity: "Integrity",
    integrityDesc: "We conduct business with honesty and transparency.",
    sustainability: "Sustainability",
    sustainabilityDesc: "We build with the environment and future generations in mind.",
    achievements: "Our Achievements",
    projectsDelivered: "Projects Delivered",
    happyFamilies: "Happy Families",
    sqftDeveloped: "Sq.Ft Developed",
    awards: "Industry Awards",
    featuredProjects: "Featured Projects",
    featuredProjectsDesc: "Discover our portfolio of exceptional developments across Dubai",
    ourProjects: "Our Projects",
    ourProjectsDesc: "Explore our diverse portfolio of residential and commercial developments",
    completed: "Completed",
    underConstruction: "Under Construction",
    launching: "Launching Soon",
    allCategories: "All",
    residential: "Residential",
    commercial: "Commercial",
    allStatuses: "All Status",
    filterBy: "Filter By",
    projectsFound: "Projects Found",
    noProjectsFound: "No projects match your filters",
    clientReviews: "Client Reviews",
    reviewsDesc: "Hear what our valued clients have to say about their experience with us",
    leaveReview: "Leave a Review",
    yourName: "Your Name",
    enterName: "Enter your name",
    projectName: "Project Name (Optional)",
    enterProject: "Enter project name",
    rating: "Rating",
    yourReview: "Your Review",
    writeReview: "Write your review here...",
    submitReview: "Submit Review",
    thankYou: "Thank You!",
    viewAllReviews: "View All Reviews",
    reviewsFound: "Reviews",
    filterByRating: "Filter by Rating",
    allRatings: "All Ratings",
    stars: "Stars",
    star: "Star",
    noReviewsFound: "No reviews match your filters",
    bookAppointment: "Book an Appointment",
    fillFormBelow: "Fill out the form below and our team will contact you shortly",
    fullName: "Full Name",
    enterFullName: "Enter your full name",
    email: "Email Address",
    enterEmail: "Enter your email",
    telephone: "Telephone",
    enterPhone: "Enter your phone number",
    address: "Address",
    streetAddress: "Street Address",
    city: "City",
    postalCode: "Postal Code",
    interestedProject: "Interested Project",
    selectProject: "Select a project",
    comments: "Comments",
    additionalComments: "Any additional comments or questions...",
    submitBooking: "Submit Booking",
    thankYouMessage: "Thank You!",
    bookingConfirmation: "We've received your booking request and will contact you soon!",
    signIn: "Sign In",
    signUp: "Sign Up",
    signOut: "Sign Out",
    signInDesc: "Welcome back! Please sign in to your account",
    signUpDesc: "Create a new account to get started",
    password: "Password",
    enterPassword: "Enter your password",
    confirmPassword: "Confirm Password",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    createAccount: "Create Account",
    creatingAccount: "Creating Account...",
    signingIn: "Signing In...",
    signInError: "Invalid email or password",
    signUpError: "Failed to create account",
    passwordMismatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 6 characters",
    profile: "Profile",
    myProfile: "My Profile",
    dashboard: "Dashboard",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    profileDetails: "Profile Details",
    manageProfileInfo: "Manage your personal information and preferences",
    notProvided: "Not provided",
    memberSince: "Member Since",
    welcome: "Welcome",
    dashboardDesc: "Manage your account and view your activity",
    myProperties: "My Properties",
    myReviews: "My Reviews",
    myBookings: "My Bookings",
    messages: "Messages",
    settings: "Settings",
    analytics: "Analytics",
    manageUsers: "Manage Users",
    manageProjects: "Manage Projects",
    allReviews: "All Reviews",
    quickStats: "Quick Stats",
    totalBookings: "Total Bookings",
    activeProperties: "Active Properties",
    reviewsGiven: "Reviews Given",
    photoUpload: "Photo Upload",
    uploadPhotos: "Upload Photos",
    uploadPhotosDesc: "Drag and drop or click to select photos",
    selectFiles: "Select Files",
    uploadedPhotos: "Uploaded Photos",
    noPhotosYet: "No photos uploaded yet",
    bookingMessages: "Booking Messages",
    noMessagesYet: "No messages received yet",
    reviewManagement: "Review Management",
    noReviewsYet: "No reviews to display",
    published: "Published",
    unpublished: "Unpublished",
    publish: "Publish",
    unpublish: "Unpublish",
  },
  ar: {
    about: "حول",
    communities: "المجتمعات",
    projects: "المشاريع",
    retail: "التجزئة",
    media: "الإعلام",
    events: "الفعاليات",
    bookNow: "احجز الآن",
    discover: "اكتشف",
    visionaryCity: "مدينة رؤيوية",
    callsFor: "تدعو إلى",
    innovativeLiving: "حياة مبتكرة",
    language: "English",
    luxuryLiving: "إعادة تعريف الحياة الفاخرة",
    exploreCommunities: "استكشف مجتمعاتنا",
    worldClass: "وسائل راحة عالمية المستوى",
    sustainableFuture: "بناء مستقبل مستدام",
    contactUs: "اتصل بنا",
    phone: "الهاتف",
    aboutUs: "معلومات عنا",
    ourStory: "قصتنا",
    ourStoryDesc:
      "منذ نشأتنا، كنا في طليعة تطوير العقارات الفاخرة، وإنشاء مجتمعات مميزة تعيد تعريف الحياة العصرية. التزامنا بالتميز والابتكار جعلنا اسمًا موثوقًا به في الصناعة.",
    ourVision: "رؤيتنا",
    ourVisionDesc:
      "إنشاء مجتمعات نابضة بالحياة ومستدامة تعزز جودة حياة السكان مع المساهمة في المشهد العمراني. نتصور مستقبلًا حيث تلتقي الفخامة بالوظيفة، ويقود الابتكار كل جانب من جوانب التطوير.",
    ourMission: "مهمتنا",
    ourMissionDesc:
      "تقديم تطويرات عقارية استثنائية تتجاوز التوقعات من خلال التصميم المبتكر والحرفية الجيدة والنهج الذي يركز على العملاء. نحن ملتزمون ببناء مجتمعات تصمد أمام اختبار الزمن.",
    coreValues: "القيم الأساسية",
    excellence: "التميز",
    excellenceDesc: "نسعى إلى أعلى المعايير في كل مشروع نقوم به.",
    innovation: "الابتكار",
    innovationDesc: "نتبنى التكنولوجيا المتطورة والحلول الإبداعية.",
    integrity: "النزاهة",
    integrityDesc: "نقوم بأعمالنا بصدق وشفافية.",
    sustainability: "الاستدامة",
    sustainabilityDesc: "نبني مع مراعاة البيئة والأجيال القادمة.",
    achievements: "إنجازاتنا",
    projectsDelivered: "المشاريع المنجزة",
    happyFamilies: "العائلات السعيدة",
    sqftDeveloped: "قدم مربع مطور",
    awards: "الجوائز الصناعية",
    featuredProjects: "المشاريع المميزة",
    featuredProjectsDesc: "اكتشف محفظة التطويرات الاستثنائية عبر دبي",
    ourProjects: "مشاريعنا",
    ourProjectsDesc: "استكشف محفظتنا المتنوعة من التطويرات السكنية والتجارية",
    completed: "مكتمل",
    underConstruction: "قيد الإنشاء",
    launching: "قريباً",
    allCategories: "الكل",
    residential: "سكني",
    commercial: "تجاري",
    allStatuses: "جميع الحالات",
    filterBy: "تصفية حسب",
    projectsFound: "مشروع",
    noProjectsFound: "لا توجد مشاريع تطابق الفلاتر",
    clientReviews: "آراء العملاء",
    reviewsDesc: "استمع إلى ما يقوله عملاؤنا الكرام عن تجربتهم معنا",
    leaveReview: "اترك تقييم",
    yourName: "اسمك",
    enterName: "أدخل اسمك",
    projectName: "اسم المشروع (اختياري)",
    enterProject: "أدخل اسم المشروع",
    rating: "التقييم",
    yourReview: "تقييمك",
    writeReview: "اكتب تقييمك هنا...",
    submitReview: "إرسال التقييم",
    thankYou: "شكراً لك!",
    viewAllReviews: "عرض جميع التقييمات",
    reviewsFound: "تقييم",
    filterByRating: "تصفية حسب التقييم",
    allRatings: "جميع التقييمات",
    stars: "نجوم",
    star: "نجمة",
    noReviewsFound: "لا توجد تقييمات تطابق الفلاتر",
    bookAppointment: "احجز موعد",
    fillFormBelow: "املأ النموذج أدناه وسيتصل بك فريقنا قريباً",
    fullName: "الاسم الكامل",
    enterFullName: "أدخل اسمك الكامل",
    email: "البريد الإلكتروني",
    enterEmail: "أدخل بريدك الإلكتروني",
    telephone: "الهاتف",
    enterPhone: "أدخل رقم هاتفك",
    address: "العنوان",
    streetAddress: "عنوان الشارع",
    city: "المدينة",
    postalCode: "الرمز البريدي",
    interestedProject: "المشروع المهتم به",
    selectProject: "اختر مشروع",
    comments: "التعليقات",
    additionalComments: "أي تعليقات أو أسئلة إضافية...",
    submitBooking: "إرسال الحجز",
    thankYouMessage: "شكراً لك!",
    bookingConfirmation: "لقد استلمنا طلب الحجز الخاص بك وسنتصل بك قريباً!",
    signIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    signOut: "تسجيل الخروج",
    signInDesc: "مرحباً بعودتك! يرجى تسجيل الدخول إلى حسابك",
    signUpDesc: "إنشاء حساب جديد للبدء",
    password: "كلمة المرور",
    enterPassword: "أدخل كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    dontHaveAccount: "ليس لديك حساب؟",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    createAccount: "إنشاء حساب",
    creatingAccount: "جاري إنشاء الحساب...",
    signingIn: "جاري تسجيل الدخول...",
    signInError: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    signUpError: "فشل في إنشاء الحساب",
    passwordMismatch: "كلمات المرور غير متطابقة",
    passwordTooShort: "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
    profile: "الملف الشخصي",
    myProfile: "ملفي الشخصي",
    dashboard: "لوحة التحكم",
    editProfile: "تعديل الملف الشخصي",
    saveChanges: "حفظ التغييرات",
    cancel: "إلغاء",
    profileDetails: "تفاصيل الملف الشخصي",
    manageProfileInfo: "إدارة معلوماتك الشخصية وتفضيلاتك",
    notProvided: "غير متوفر",
    memberSince: "عضو منذ",
    welcome: "مرحباً",
    dashboardDesc: "إدارة حسابك وعرض نشاطك",
    myProperties: "عقاراتي",
    myReviews: "تقييماتي",
    myBookings: "حجوزاتي",
    messages: "الرسائل",
    settings: "الإعدادات",
    analytics: "التحليلات",
    manageUsers: "إدارة المستخدمين",
    manageProjects: "إدارة المشاريع",
    allReviews: "جميع التقييمات",
    quickStats: "إحصائيات سريعة",
    totalBookings: "إجمالي الحجوزات",
    activeProperties: "العقارات النشطة",
    reviewsGiven: "التقييمات المقدمة",
    photoUpload: "تحميل الصور",
    uploadPhotos: "تحميل الصور",
    uploadPhotosDesc: "اسحب وأفلت أو انقر لتحديد الصور",
    selectFiles: "اختر الملفات",
    uploadedPhotos: "الصور المرفوعة",
    noPhotosYet: "لم يتم تحميل أي صور بعد",
    bookingMessages: "رسائل الحجز",
    noMessagesYet: "لم يتم استلام أي رسائل بعد",
    reviewManagement: "إدارة التقييمات",
    noReviewsYet: "لا توجد تقييمات لعرضها",
    published: "منشور",
    unpublished: "غير منشور",
    publish: "نشر",
    unpublish: "إلغاء النشر",
  },
} 
