// Shared styles and utility classes
export const styles = {
  container: "container mx-auto px-4 md:px-6 lg:px-8",
  section: "py-16 md:py-24",
  heading: "text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight",
  subheading: "text-2xl md:text-3xl lg:text-4xl font-bold",

  button: {
    primary:
      "px-6 py-3 bg-primary text-primary-foreground hover:bg-primary/90 transition-colors font-medium",
    outline:
      "px-6 py-3 border-2 border-primary text-primary hover:bg-primary hover:text-primary-foreground transition-colors font-medium"
  },

  overlay: "absolute inset-0 bg-black/40",
  fadeIn: "animate-fade-in"
}

export const translations = {
  en: {
    about: "ABOUT",
    communities: "COMMUNITIES",
    projects: "PROJECTS",
    retail: "RETAIL",
    media: "MEDIA",
    events: "EVENTS",
    bookNow: "BOOK NOW",
    discover: "DISCOVER",
    visionaryCity: "A VISIONARY CITY",
    callsFor: "CALLS FOR",
    innovativeLiving: "INNOVATIVE LIVING",
    language: "العربية",
    luxuryLiving: "Luxury Living Redefined",
    exploreCommunities: "Explore Our Communities",
    worldClass: "World-Class Amenities",
    sustainableFuture: "Building a Sustainable Future",
    contactUs: "Contact Us",
    phone: "Phone",
    aboutUs: "About Us",
    ourStory: "Our Story",
    ourStoryDesc:
      "Since our inception, we have been at the forefront of luxury real estate development, creating iconic communities that redefine modern living. Our commitment to excellence and innovation has established us as a trusted name in the industry.",
    ourVision: "Our Vision",
    ourVisionDesc:
      "To create vibrant, sustainable communities that enhance the quality of life for residents while contributing to the urban landscape. We envision a future where luxury meets functionality, and innovation drives every aspect of development.",
    ourMission: "Our Mission",
    ourMissionDesc:
      "To deliver exceptional real estate developments that exceed expectations through innovative design, quality craftsmanship, and customer-centric approach. We are committed to building communities that stand the test of time.",
    coreValues: "Core Values",
    excellence: "Excellence",
    excellenceDesc:
      "We pursue the highest standards in every project we undertake.",
    innovation: "Innovation",
    innovationDesc:
      "We embrace cutting-edge technology and creative solutions.",
    integrity: "Integrity",
    integrityDesc: "We conduct business with honesty and transparency.",
    sustainability: "Sustainability",
    sustainabilityDesc:
      "We build with the environment and future generations in mind.",
    achievements: "Our Achievements",
    projectsDelivered: "Projects Delivered",
    happyFamilies: "Happy Families",
    sqftDeveloped: "Sq.Ft Developed",
    awards: "Industry Awards",
    featuredProjects: "Featured Projects",
    featuredProjectsDesc:
      "Discover our portfolio of exceptional developments across Dubai",
    ourProjects: "Our Projects",
    ourProjectsDesc:
      "Explore our diverse portfolio of residential and commercial developments",
    completed: "Completed",
    underConstruction: "Under Construction",
    launching: "Launching Soon",
    allCategories: "All",
    residential: "Residential",
    commercial: "Commercial",
    allStatuses: "All Status",
    filterBy: "Filter By",
    projectsFound: "Projects Found",
    noProjectsFound: "No projects match your filters",
    clientReviews: "CLIENT REVIEWS",
    reviewsDesc:
      "Hear what our valued clients have to say about their experience with us",
    leaveReview: "Leave a Review",
    yourName: "Your Name",
    enterName: "Enter your name",
    projectName: "Project Name (Optional)",
    enterProject: "Enter project name",
    rating: "Rating",
    yourReview: "Your Review",
    writeReview: "Write your review here...",
    submitReview: "Submit Review",
    thankYou: "Thank You!",
    viewAllReviews: "View All Reviews",
    reviewsFound: "Reviews",
    filterByRating: "Filter by Rating",
    allRatings: "All Ratings",
    stars: "Stars",
    star: "Star",
    noReviewsFound: "No reviews match your filters"
  },

  ar: {
    about: "حول",
    communities: "المجتمعات",
    projects: "المشاريع",
    retail: "التجزئة",
    media: "الإعلام",
    events: "الفعاليات",
    bookNow: "احجز الآن",
    discover: "اكتشف",
    visionaryCity: "مدينة رؤيوية",
    callsFor: "تدعو إلى",
    innovativeLiving: "حياة مبتكرة",
    language: "English",
    luxuryLiving: "إعادة تعريف الحياة الفاخرة",
    exploreCommunities: "استكشف مجتمعاتنا",
    worldClass: "وسائل راحة عالمية المستوى",
    sustainableFuture: "بناء مستقبل مستدام",
    contactUs: "اتصل بنا",
    phone: "الهاتف",
    aboutUs: "معلومات عنا",
    ourStory: "قصتنا",
    ourStoryDesc:
      "منذ نشأتنا، كنا في طليعة تطوير العقارات الفاخرة، وإنشاء مجتمعات مميزة تعيد تعريف الحياة العصرية. التزامنا بالتميز والابتكار جعلنا اسمًا موثوقًا به في الصناعة.",
    ourVision: "رؤيتنا",
    ourVisionDesc:
      "إنشاء مجتمعات نابضة بالحياة ومستدامة تعزز جودة حياة السكان مع المساهمة في المشهد العمراني. نتصور مستقبلًا حيث تلتقي الفخامة بالوظيفة، ويقود الابتكار كل جانب من جوانب التطوير.",
    ourMission: "مهمتنا",
    ourMissionDesc:
      "تقديم تطويرات عقارية استثنائية تتجاوز التوقعات من خلال التصميم المبتكر والحرفية الجيدة والنهج الذي يركز على العملاء. نحن ملتزمون ببناء مجتمعات تصمد أمام اختبار الزمن.",
    coreValues: "القيم الأساسية",
    excellence: "التميز",
    excellenceDesc: "نسعى إلى أعلى المعايير في كل مشروع نقوم به.",
    innovation: "الابتكار",
    innovationDesc: "نتبنى التكنولوجيا المتطورة والحلول الإبداعية.",
    integrity: "النزاهة",
    integrityDesc: "نقوم بأعمالنا بصدق وشفافية.",
    sustainability: "الاستدامة",
    sustainabilityDesc: "نبني مع مراعاة البيئة والأجيال القادمة.",
    achievements: "إنجازاتنا",
    projectsDelivered: "المشاريع المنجزة",
    happyFamilies: "العائلات السعيدة",
    sqftDeveloped: "قدم مربع مطور",
    awards: "الجوائز الصناعية",
    featuredProjects: "المشاريع المميزة",
    featuredProjectsDesc: "اكتشف محفظة التطويرات الاستثنائية عبر دبي",
    ourProjects: "مشاريعنا",
    ourProjectsDesc: "استكشف محفظتنا المتنوعة من التطويرات السكنية والتجارية",
    completed: "مكتمل",
    underConstruction: "قيد الإنشاء",
    launching: "قريباً",
    allCategories: "الكل",
    residential: "سكني",
    commercial: "تجاري",
    allStatuses: "جميع الحالات",
    filterBy: "تصفية حسب",
    projectsFound: "مشروع",
    noProjectsFound: "لا توجد مشاريع تطابق الفلاتر",
    clientReviews: "آراء العملاء",
    reviewsDesc: "استمع إلى ما يقوله عملاؤنا الكرام عن تجربتهم معنا",
    leaveReview: "اترك تقييم",
    yourName: "اسمك",
    enterName: "أدخل اسمك",
    projectName: "اسم المشروع (اختياري)",
    enterProject: "أدخل اسم المشروع",
    rating: "التقييم",
    yourReview: "تقييمك",
    writeReview: "اكتب تقييمك هنا...",
    submitReview: "إرسال التقييم",
    thankYou: "شكراً لك!",
    viewAllReviews: "عرض جميع التقييمات",
    reviewsFound: "تقييم",
    filterByRating: "تصفية حسب التقييم",
    allRatings: "جميع التقييمات",
    stars: "نجوم",
    star: "نجمة",
    noReviewsFound: "لا توجد تقييمات تطابق الفلاتر"
  }
}
